name: UAT Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-to-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to UAT
        run: npm run deploy-uat
